services:
  teddy_backend_api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mysql://teddy:teddy@mysql_db:3307/teddy?schema=public
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teddy
      MYSQL_USER: teddy
      MYSQL_PASSWORD: teddy
      MYSQL_TCP_PORT: 3307