services:
  db:
    container_name: mysql_db
    image: mysql
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teddy
      MYSQL_USER: teddy
      MYSQL_PASSWORD: teddy
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  teddy_backend_api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        # restart: true
    ports:
      - '3944:3944'
    env_file:
      - .deployment.env
    volumes:
      - ./src:/usr/src/app/src